1D Array

In [10]:
import numpy as np

In [11]:
arr_1d = np.array([1,2,3,4])
print(arr_1d)

[1 2 3 4]


In [12]:
type(arr_1d)

numpy.ndarray

In [13]:
arr_1d.ndim

1

In [14]:
arr_1d.size

4

In [19]:
arr_1d.shape

(4,)

2D Array

In [15]:
arr_2d = np.array([[1,2,3,4], [5,6,7,8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
arr_2d.ndim

2

In [17]:
arr_2d.size

8

In [20]:
arr_2d.shape

(2, 4)

In [21]:
arr_2d.dtype

dtype('int64')