Numpy Matrix

In [10]:
import numpy as np

In [11]:
mx_1 = np.array([[1,1,1,], [1,1,1], [1,1,1]])
print(mx_1)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [12]:
mx_1 = np.ones(5)
print(mx_1)
mx_1.dtype

[1. 1. 1. 1. 1.]


dtype('float64')

In [13]:
mx_1 = np.ones((3,4)) #row 3, colums 4
print(mx_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
mx_1 = np.ones((3,4),dtype = int)
print(mx_1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [20]:
mx_0 = np.zeros((4,6))
print(mx_0)


[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [22]:
mx_0 = np.zeros((4,6),dtype= bool)
print(mx_0)

[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]


In [24]:
mx_0 = np.zeros((4,6),dtype= str)
print(mx_0)

[['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']
 ['' '' '' '' '' '']]


In [26]:
emt_str = ""
print(bool(emt_str))

False


In [27]:
emt_str = " "
print(bool(emt_str))

True


In [28]:
emt_matrix = np.empty((3,3))
print(emt_matrix)

[[5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]
 [5.e-324 5.e-324 5.e-324]]
