# NumPy Functions

In [18]:
import numpy as np

arange()

In [19]:
#np.arange(start, End, step)
arr_1d = np.arange(1,13)
print(arr_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [20]:
even_arr = np.arange(2,13,2)
print(even_arr)

[ 2  4  6  8 10 12]


In [21]:
odd_arr = np.arange(1,13,2)
print(odd_arr)

[ 1  3  5  7  9 11]


linspace()

In [22]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

reshape()

In [23]:
arr_2d = arr_1d.reshape(2,6)
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [24]:
arr_2d = arr_1d.reshape(3,4)
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
arr_3d = arr_1d.reshape(2,3,2)
print(arr_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [26]:
arr = np.arange(1,13).reshape(2,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


ravel()

In [29]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

flatten()

In [30]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

transpose()

In [31]:
arr.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 4, 10],
       [ 5, 11],
       [ 6, 12]])