# Random Sampling 

In [2]:
import numpy as np
import random

In [3]:
np.random.random(1)

array([0.09928219])

In [4]:
np.random.random((3,3))

array([[0.57838268, 0.09413916, 0.75816315],
       [0.58991396, 0.12248595, 0.53504328],
       [0.01009366, 0.72783806, 0.91049407]])

In [8]:
np.random.randint(1,4)

3

In [10]:
np.random.randint(1,4, (4,4))

array([[1, 1, 3, 1],
       [1, 3, 3, 1],
       [2, 1, 2, 3],
       [3, 3, 1, 3]])

In [11]:
np.random.randint(1,4, (2,4,4))

array([[[3, 3, 3, 1],
        [1, 1, 2, 1],
        [3, 2, 1, 2],
        [3, 3, 3, 1]],

       [[1, 1, 1, 2],
        [2, 2, 2, 3],
        [3, 3, 3, 2],
        [3, 3, 1, 3]]])

In [12]:
np.random.seed(10)
np.random.randint(1,4, (2,4,4))

array([[[2, 2, 1, 1],
        [2, 1, 2, 2],
        [1, 2, 2, 3],
        [1, 2, 1, 3]],

       [[1, 3, 1, 1],
        [1, 3, 1, 3],
        [3, 2, 1, 1],
        [3, 2, 3, 2]]])

In [13]:
2**32 - 1

4294967295

In [14]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [15]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [16]:
np.random.randn(3,3)

array([[-1.58494101,  1.05535316, -1.92657911],
       [ 0.69858388, -0.74620143, -0.15662666],
       [-0.19363594,  1.13912535,  0.36221796]])

In [17]:
x = [1,2,3,4]
np.random.choice(x)

np.int64(1)

In [18]:
np.random.choice(x)


np.int64(1)

In [19]:
np.random.choice(x)

np.int64(1)

In [20]:
for i in range(20):
    print(np.random.choice(x))

2
1
4
1
1
3
1
3
3
1
4
2
1
4
2
3
3
2
3
3


In [21]:
x

[1, 2, 3, 4]

In [22]:
np.random.permutation(x)

array([2, 3, 1, 4])

In [23]:
np.random.permutation(x)

array([2, 3, 4, 1])